---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install desired base packages.
      package:
        name:
          - htop
          - tmux
          - vim-nox
