---
- name: install desired base packages.
  apt:
    name:
      - dconf-cli
      - htop
      - python3-psutil
      - tmux
      - vim-nox
  state: present

- name: copy wallpaper file.
  copy:
    src: files/wallpaper.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root

- name: set wallpaper.
  become_user: cmesserli
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

- name: set wallpaper position.
  become_user: cmesserli
  dconf:
    key: "org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: copy .bashrc file.
  copy:
    src: files/bashrc
    dest: /home/cmesserli/.bashrc
    owner: cmesserli
    group: cmesserli
